CREATE TABLE GARUREG(USID INT NOT NULL PRIMARY KEY,UNAME CHAR(20),USERNAME VARCHAR(20),PASS VARCHAR(20),REPASS VARCHAR(20),DOB VARCHAR(15),GENDER CHAR(8),MOBILENO NUMBER(10),EMAILID VARCHAR(20),ADDRESS VARCHAR(40),PRIVILAGE CHAR(1));
SELECT * FROM GARUREG;
DROP TABLE GARUREG;
DELETE FROM GARUREG WHERE USID=3;
DELETE FROM TASKUSERDATA WHERE USID=3;
UPDATE TASKUSERDATA SET USID=2 WHERE PROCESS='NARAYANAN';

CREATE TABLE TASKUSERDATA(USID INT NOT NULL REFERENCES GARUREG,CAREERID INT NOT NULL PRIMARY KEY,DEPT CHAR(20),PROCESS CHAR(30),POSITION CHAR(30),CRDATE VARCHAR(20));
SELECT *  FROM TASKUSERDATA; 
drop table TASKUSERDATA;

CREATE TABLE TASKPROJECT(PRJID INT NOT NULL PRIMARY KEY, PRJNAME CHAR(40),PRJLAN VARCHAR(20),STDATE VARCHAR(20), ENDATE VARCHAR(20));
SELECT *  FROM TASKPROJECT;

CREATE TABLE TMSTASK(TASKID INT NOT NULL PRIMARY KEY,TASKNAME VARCHAR(30),DURATION VARCHAR(30));
SELECT *  FROM TMSTASK;

SELECT USID FROM GARUREG WHERE UNAME= 'Dineshkumar         ';

CREATE TABLE FEEDBACKDETAILS(FID INT NOT NULL PRIMARY KEY,ENTRYDATE VARCHAR(15),UNAME CHAR(20),POSITION VARCHAR(30),PROCESS VARCHAR(30),DEPT CHAR(30),DESCR VARCHAR(100));
SELECT * FROM FEEDBACKDETAILS;
drop table FEEDBACKDETAILS;  
SELECT MAX(FID) FROM FEEDBACKDETAILS;

commit;

update TASKPROJECT set PRJNAME='ebill' where PRJID=1;
   
    CREATE VIEW profiledata as SELECT US.USID,UNAME,CAREERID,CRDATE,DOB,POSITION,PROCESS,DEPT,GENDER,MOBILENO,EMAILID,ADDRESS 
FROM GARUREG US,TASKUSERDATA PRO WHERE US.USID=PRO.USID ORDER BY US.USID;
SELECT * FROM profiledata;
DROP VIEW profiledata;
   
CREATE TABLE TKUSERACT(USID INT NOT NULL REFERENCES GARUREG,SNO INT NOT NULL PRIMARY KEY,USERNAME CHAR(30),WRDATE VARCHAR(20),PRNAME VARCHAR(40),TECHNOLOGY VARCHAR(10),SCREENNAME VARCHAR(20),TKACTION VARCHAR(200));

CREATE OR REPLACE TRIGGER books_on_insert
  BEFORE INSERT ON books
  FOR EACH ROW
BEGIN
  SELECT books_sequence.nextval
  INTO :new.id
  FROM dual;
END;

CREATE SEQUENCE TKUSERACT_SNO
 MINVALUE       -1
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 DROP SEQUENCE TKUSERACT_SNO;
 
SELECT * FROM TKUSERACT;

DELETE FROM TKUSERACT;